project-visualforce/BasePackage/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

packages/BasePackage/main/default/objects/Team__c/fields/Pokemon_1__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_1__c</fullName>
    <label>Pokemon 1</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

packages/BasePackage/main/default/objects/Team__c/fields/Pokemon_2__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_2__c</fullName>
    <label>Pokemon 2</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

packages/BasePackage/main/default/objects/Team__c/fields/Pokemon_3__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_3__c</fullName>
    <label>Pokemon 3</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

packages/BasePackage/main/default/objects/Team__c/fields/Pokemon_4__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_4__c</fullName>
    <label>Pokemon 4</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

project-visualforce/BasePackage/main/default/objects/Team__c/fields/Pokemon_5__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_5__c</fullName>
    <label>Pokemon 5</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

project-visualforce/BasePackage/main/default/objects/Team__c/fields/Pokemon_6__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_6__c</fullName>
    <label>Pokemon 6</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

project-visualforce/PokeBattle/main/default/classes/VFBattleExtension.cls
public with sharing class VFBattleExtension {

    private final Team__c team;
    public VFBattleExtension(ApexPages.StandardController stdController) {
        this.team = (team__c)stdController.getRecord();
    }

    public String getTeam(){
        return 'Team Name: ' + team.name;
    }

    public list<Team__c> homeTeam = [SELECT Id, Name, Pokemon_1__c, Pokemon_2__c, Pokemon_3__c, Pokemon_4__c, Pokemon_5__c, Pokemon_6__c FROM Team__c];
    public list<String> opponentTeam = new list<String>();
    opponentTeam.add();



    public integer Battle(){
        integer intrandom = Integer.valueof((Math.random() * 2 ));
        //return type must be page reference.   fix later
        return intrandom;
    }
}