project-visualforce/BasePackage/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

packages/BasePackage/main/default/objects/Team__c/fields/Pokemon_1__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_1__c</fullName>
    <label>Pokemon 1</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

packages/BasePackage/main/default/objects/Team__c/fields/Pokemon_2__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_2__c</fullName>
    <label>Pokemon 2</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

packages/BasePackage/main/default/objects/Team__c/fields/Pokemon_3__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_3__c</fullName>
    <label>Pokemon 3</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

packages/BasePackage/main/default/objects/Team__c/fields/Pokemon_4__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_4__c</fullName>
    <label>Pokemon 4</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

project-visualforce/BasePackage/main/default/objects/Team__c/fields/Pokemon_5__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_5__c</fullName>
    <label>Pokemon 5</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

project-visualforce/BasePackage/main/default/objects/Team__c/fields/Pokemon_6__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_6__c</fullName>
    <label>Pokemon 6</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

project-visualforce/BasePackage/main/default/objects/Team__c/fields/Team_Loss__c.field-meta.xml
<CustomField>
    <fullName>Team_Loss__c</fullName>
    <label>Team_Loss</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

project-visualforce/BasePackage/main/default/objects/Team__c/fields/Team_Win__c.field-meta.xml
<CustomField>
    <fullName>Team_Win__c</fullName>
    <label>Team Win</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

project-visualforce/TeamList/main/default/classes/PreviousTeamEditDeleteController_CC.cls
public with sharing class PreviousTeamEditDeleteController_CC{
    
	public List<Team__c> teams { get; set; }
  
   //used to get a hold of the team record selected for deletion
   public string SelectedTeamId { get; set; }
  
   public PreviousTeamEditDeleteController_CC() {
       //load team data into our DataTable
       LoadData();
   }
  
   private void LoadData() {
       teams = [SELECT id, Name, Pokemon_1__c,Pokemon_2__c,Pokemon_3__c,Pokemon_4__c,Pokemon_5__c,Pokemon_6__c,Team_Win__c, Team_Loss__c FROM Team__c limit 20];
   }
  
   public void DeleteTeam()
   {
      // if for any reason we are missing the reference 
      if (SelectedTeamId == null) {
      
         return;
      }
     
      // find the team record within the collection
      Team__c tobeDeleted = null;
      for(Team__c tea : teams)
       if (tea.Id == SelectedTeamId) {
          tobeDeleted = tea;
          break;
       }
      
      //if team record found delete it
      if (tobeDeleted != null) {
       Delete tobeDeleted;
      }
     
      //refresh the data
      LoadData();
   }    
  
  
}