project-visualforce/packages/BasePackage/main/default/objects/Battle__c/Battle__c.object-meta.xml
<CustomObject>
    <description>Battle object for Pokemon App.</description>
    <label>Battle</label>
    <nameField>
        <label>Battle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Battles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

project-visualforce/BasePackage/main/default/objects/Battle__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Host for current battle</description>
    <inlineHelpText>Select a hosting trainer.</inlineHelpText>
    <label>Host</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Battles (Host)</relationshipLabel>
    <relationshipName>HostBattles</relationshipName>
    <type>Lookup</type>
</CustomField>

project-visualforce/TeamListPackage/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Battle participants for Pokemon App</description>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

project-visualforce/TeamListPackage/main/default/objects/Participant__c/fields/Battle__c.field-meta.xml
<CustomField>
    <fullName>Battle__c</fullName>
    <description>The participant&apos;s battle</description>
    <inlineHelpText>Select this participant&apos;s battle.</inlineHelpText>
    <label>Battle</label>
    <referenceTo>Battle__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

project-visualforce/TeamListPackage/main/default/objects/Participant__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team participating in a battle</description>
    <inlineHelpText>Select a team that will be participating.</inlineHelpText>
    <label>Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Team__c.Trainer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Trainer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

project-visualforce/TeamListPackage/main/default/objects/Participant__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Trainer participating in a battle</description>
    <inlineHelpText>Select a trainer who will be participating.</inlineHelpText>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

project-visualforce/BasePackage/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

project-visualforce/packages/BasePackage/main/default/objects/Team__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Trainer for current team</description>
    <inlineHelpText>Select a trainer for this team.</inlineHelpText>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

project-visualforce/TeamListPackage/main/default/classes/PreBattleController.cls
public class PreBattleController {
    final Battle__c battle;
    final Participant__c host;
    final List<Participant__c> guests;
    public String opponent { get; set; }
    public String opponentHelpText { get; private set; }
    public String opponentURL { get; set; }
    public Boolean showOpponentURL { 
        get {
            return (opponent == FROM_URL);
        }
    }
    
    public static final String RANDOM = 'Random';
    public static final String FROM_URL = 'From URL';
    
    public PreBattleController() {
        Map<String, String> params = ApexPages.currentPage().getParameters();
        String battleId = params.get('Id');
        System.debug(battleId);
       	
        /*
        // if no battleId, create new battle. otherwise, retrieve current battleId. 
        if (battleId != null) {
        	this.battle = SiteUtils.getSObject('Battle__c', battleId);
        } else {
            // battle name will be Trainer vs Trainer and assigned later.
            this.battle = new Battle();
        }
        // attempt to find a host. if no host is found, assign current user as host.
        try {
            this.host = [SELECT Name, Trainer__c, Team__c FROM Participant__c WHERE Battle__c=:this.battle.Id AND Id=:this.battle.Host__c];
        } catch (QueryException e) {
            String trainerId = '0031700001KRXCMAA5'; // hardcoding id works
            Participant__c host = new Participant__c(Trainer__c=trainerId, Battle__c=this.battle.Id);
            insert host;
            this.host = host;
        }
        this.guests = [SELECT Name, Trainer__c, Team__c FROM Participant__c WHERE Battle__c=:this.battle.Id AND Id!=:this.battle.Host__c];
        this.opponent = RANDOM;
        this.opponentHelpText = 'Select an opposing team source.';
        this.opponentURL = '';
*/
    }
}