project-visualforce/packages/BasePackage/main/default/objects/Battle__c/Battle__c.object-meta.xml
<CustomObject>
    <description>Battle object for Pokemon App.</description>
    <label>Battle</label>
    <nameField>
        <label>Battle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Battles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

project-visualforce/BasePackage/main/default/objects/Battle__c/fields/Guest_Type__c.field-meta.xml
<CustomField>
    <fullName>Guest_Type__c</fullName>
    <defaultValue>&quot;CPU&quot;</defaultValue>
    <description>Determines whether the guest trainer is human- or AI-controlled</description>
    <inlineHelpText>Choose whether the guest trainer is human- or AI-controlled.</inlineHelpText>
    <label>Guest Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TrainerType</valueSetName>
    </valueSet>
</CustomField>

project-visualforce/BasePackage/main/default/objects/Battle__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Host for current battle</description>
    <inlineHelpText>Select a hosting trainer.</inlineHelpText>
    <label>Host</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Battles (Host)</relationshipLabel>
    <relationshipName>HostBattles</relationshipName>
    <type>Lookup</type>
</CustomField>

project-visualforce/TeamListPackage/main/default/objects/Participant__c/Participant__c.object-meta.xml
<CustomObject>
    <description>Battle participants for Pokemon App</description>
    <label>Participant</label>
    <nameField>
        <label>Participant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

project-visualforce/TeamListPackage/main/default/objects/Participant__c/fields/Battle__c.field-meta.xml
<CustomField>
    <fullName>Battle__c</fullName>
    <description>The participant&apos;s battle</description>
    <inlineHelpText>Select this participant&apos;s battle.</inlineHelpText>
    <label>Battle</label>
    <referenceTo>Battle__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

project-visualforce/TeamListPackage/main/default/objects/Participant__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Team participating in a battle</description>
    <inlineHelpText>Select a team that will be participating.</inlineHelpText>
    <label>Team</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Team__c.Trainer__c</field>
            <operation>equals</operation>
            <valueField>$Source.Trainer__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

project-visualforce/TeamListPackage/main/default/objects/Participant__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Trainer participating in a battle</description>
    <inlineHelpText>Select a trainer who will be participating.</inlineHelpText>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Participants</relationshipLabel>
    <relationshipName>Participants</relationshipName>
    <type>Lookup</type>
</CustomField>

project-visualforce/BasePackage/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

packages/BasePackage/main/default/objects/Team__c/fields/Pokemon_1__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_1__c</fullName>
    <label>Pokemon 1</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

packages/BasePackage/main/default/objects/Team__c/fields/Pokemon_2__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_2__c</fullName>
    <label>Pokemon 2</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

packages/BasePackage/main/default/objects/Team__c/fields/Pokemon_3__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_3__c</fullName>
    <label>Pokemon 3</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

packages/BasePackage/main/default/objects/Team__c/fields/Pokemon_4__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_4__c</fullName>
    <label>Pokemon 4</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

project-visualforce/BasePackage/main/default/objects/Team__c/fields/Pokemon_5__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_5__c</fullName>
    <label>Pokemon 5</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

project-visualforce/BasePackage/main/default/objects/Team__c/fields/Pokemon_6__c.field-meta.xml
<CustomField>
    <fullName>Pokemon_6__c</fullName>
    <label>Pokemon 6</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

project-visualforce/packages/BasePackage/main/default/objects/Team__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Trainer for current team</description>
    <inlineHelpText>Select a trainer for this team.</inlineHelpText>
    <label>Trainer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

project-visualforce/TeamListPackage/main/default/globalValueSets/TrainerType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Human</fullName>
        <default>true</default>
        <label>Human</label>
    </customValue>
    <customValue>
        <fullName>CPU</fullName>
    </customValue>
    <description>Determine if the player is Human or AI Controlled</description>
    <masterLabel>TrainerType</masterLabel>
</GlobalValueSet>

project-visualforce/PreBattlePackage/main/default/classes/BattleExtension.cls
public class BattleExtension {
    
    final ApexPages.StandardController stdController;    
    final Battle__c battle;
    
    public Boolean hasId {
        get {
            if (this.stdController.getId() == null || this.battle.Host__c == null) return false;
            return true;
        }}
    public Participant__c host { get; private set; } 
    public List<Participant__c> guests { get; private set; }
    public String opponent { get; set; }
    public String opponentHelpText { get; private set; }
    public String opponentURL { get; set; }
    public Boolean showOpponentURL { 
        get {
            return (opponent == FROM_URL);
        }
    }
    
    public static final String RANDOM = 'Random';
    public static final String FROM_URL = 'From URL';
    public static final List<String> fieldNames = new List<String>{'Participants__r.Name'};
    
    public BattleExtension(ApexPages.StandardController stdController) {
        this.stdController = stdController;
        this.stdController.addFields(fieldNames);
        this.battle = (Battle__c) stdController.getRecord();
        
         System.debug(this.battle);
        System.debug(fieldNames);
        if (stdController.getId() != null && this.battle.Host__c != null) {
            this.host = [SELECT Name, Trainer__c, Team__c FROM Participant__c WHERE Battle__c=:this.battle.Id AND Id=:this.battle.Host__c];
            this.guests = [SELECT Name, Trainer__c, Team__c FROM Participant__c WHERE Battle__c=:this.battle.Id AND Id!=:this.battle.Host__c];
            this.opponent = RANDOM;
            this.opponentHelpText = 'Select an opposing team source.';
            this.opponentURL = '';
        }
    }
    
    public List<SelectOption> getOpponentOptions() {
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption(RANDOM, RANDOM)); 
        options.add(new SelectOption(FROM_URL, FROM_URL)); 
        return options; 
    }
    
    public PageReference refresh() {
        System.debug(ApexPages.currentPage().getParameters().get('retURL'));
        return null;
    }
    
    public PageReference save() {
        // Check if HostTeam was selected properly
        if (this.host == null) {
            return null;
        }
        // If selected guest type is CPU, generate a new CPU participant.
        if (this.battle.Guest_Type__c == 'CPU') {
            SObject oppTeam;
            if (opponent == RANDOM) {
                oppTeam = new Team__c(
                    Name = 'CPU Team',
                    Pokemon_1__c = Integer.valueof(Math.random() * (Pokemon.maxNum - 1) + 1),
                    Pokemon_2__c = Integer.valueof(Math.random() * (Pokemon.maxNum - 1) + 1),
                    Pokemon_3__c = Integer.valueof(Math.random() * (Pokemon.maxNum - 1) + 1),
                    Pokemon_4__c = Integer.valueof(Math.random() * (Pokemon.maxNum - 1) + 1),
                    Pokemon_5__c = Integer.valueof(Math.random() * (Pokemon.maxNum - 1) + 1),
                    Pokemon_6__c = Integer.valueof(Math.random() * (Pokemon.maxNum - 1) + 1)
                );
                insert oppTeam;
            } else if (opponent == FROM_URL) {
                try { 
                    Http http = new Http();
                    HttpRequest request = new HttpRequest();
                    request.setEndpoint(opponentURL);
                    request.setMethod('GET');
                    HttpResponse response = http.send(request);
                    Object resBody = JSON.deserializeUntyped(response.getBody());
                    Map<String, Object> resMap = (Map<String, Object>) resBody;
                    resMap.remove('Id');
                    
                    oppTeam = SiteUtils.createSObject('Team__c', resMap);
                    insert oppTeam;
                } catch (CalloutException e) {
                    System.debug(e);
                }
            }
            Contact trainer = CPUController.trainer;
            Participant__c guest = new Participant__c(Trainer__c=trainer.Id, Team__c=oppTeam.Id, Battle__c=this.battle.Id);
            insert guest;
            guests.add(guest);
        }
        String myTeamStr = String.valueOf(this.host.Id);
        String oppTeamStr = String.valueOf(this.guests[0].Id);
        
        // Check if GuestTeam was created properly
        if (this.guests[0] == null) {
            return null;
        }
        stdController.save();
        return new PageReference('/apex/PokemonBattle?myTeam=' + myTeamStr + '&oppTeam=' + oppTeamStr);
    }
    
}